name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

env:
  aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
  aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
  aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_REGION: "us-east-1"
  ECR_URI: ${{secrets.ECR_URI}}
  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME}}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.aws_access_key }}
          aws-secret-access-key: ${{ env.aws_secret_key }}
          aws-session-token: ${{ env.aws_session_token}}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker images
        run: |
          docker build -t multi-client:latest ./client
          docker build -t multi-server:latest ./server
          docker build -t multi-worker:latest ./worker

      - name: Tag and push Docker image
        run: |
          docker tag multi-client:latest ${{ env.ECR_URI }}:client
          docker push ${{ env.ECR_URI }}:client

          docker tag multi-server:latest ${{ env.ECR_URI }}:server
          docker push ${{ env.ECR_URI }}:server

          docker tag multi-worker:latest ${{ env.ECR_URI }}:worker
          docker push ${{ env.ECR_URI }}:worker

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "latest"

      - name: Write kubeconfig
        run: |
          mkdir -p $HOME/.kube
          aws eks update-kubeconfig --name multi_fib

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/
