name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

env:
  aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
  aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
  aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_REGION: us-east-1
  ECR_ACCOUNT: ${{ secrets.ECR_ACCOUNT }}
  ECR_REPO_NAME: fib_complex
  ECR_NAMESPACE: alwells

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.aws_access_key }}
          aws-secret-access-key: ${{ env.aws_secret_key }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker images
        run: |
          docker build -t multi-client:latest ./client
          docker build -t multi-server:latest ./server
          docker build -t multi-worker:latest ./worker

      - name: Tag Docker image
        env:
          ECR_REPO: ${{ env.ECR_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_NAMESPACE }}/${{ env.ECR_REPO_NAME }}

        run: |
          docker tag multi-client:latest ${{ env.ECR_REPO_NAME }}
          docker tag multi-server:latest ${{ env.ECR_REPO_NAME }}
          docker tag multi-worker:latest ${{ env.ECR_REPO_NAME }}

      - name: Push Docker image to ECR
        run: docker push ${{ env.ECR_REPO_NAME }}
